(add): checks if all the tx for a given dsblock are sync'ed
Zilliqa/zilliqa-relayer pull request #25
Opened 2024-03-04 18:44 UTC by mauromedda

2024-03-05 09:48 UTC, JamesHinshelwood approved these changes

2024-03-05 10:47 UTC, frankmeds approved these changes

2024-03-05 13:00 UTC, rrw-zilliqa requested changes

2024-03-05 13:00 UTC, rrw-zilliqa commented on service/zil2poly.go
> +	if err2 != nil {
This is the current polynet tx block, not the Zilliqa tx block it is synced with - for that, you need to go get data from polynet storage. Use func (s *ZilliqaSyncManager) findLatestTxBlockHeight() uint64 .

2024-03-05 13:00 UTC, rrw-zilliqa commented on service/zil2poly.go
> +	if (uint64(curr)+100)%dsNum == 99 {
Worth a comment! A more direct way to do this is to check that GetCurrentBlockHeight() is == currTxBlock.Header.BlockNum -1

2024-03-25 10:29 UTC, mauromedda commented
Not needed

2024-03-25 10:29 UTC, closed without merging